services:
  - type: web
    name: ali_baba_test-1
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn --bind 0.0.0.0:8000 alibaba.wsgi:application --workers=3"
    envVars:
      DJANGO_SETTINGS_MODULE: "alibaba.settings"  # Update to match your settings module
    staticPublishPath: staticfiles/
    routes:
      - type: static
        path: /media
        source: /media  # This serves media files from the media directory
